name: Cypress tests

on: [push]

jobs:
  start:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
      options: --ipc=host
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: 'http://localhost:3000'

        # Test run screenshots if the run fails
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

        # Test run video was always captured
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
